config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"
  get "policy", to: "static_pages#policy"
  get "terms", to: "static_pages#terms"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  # Googleログインで使用する Oauthルーディング

  resources :user_sessions, only: %i[new create destroy]
  resources :users, only: %i[new create show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :formations, only: %i[new] do
    collection do
      get "test_1"
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  # sorceryによる認証機能を持たせる

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  # if => {}:   「新しいレコード」または「crypted_passwordが変更された」
  # passwordの長さが最低3文字以上であることを要求する

  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  # password_confirmationという属性がpasswordと一致することを要求するバリデーション

  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  # passwordフィールドの確認（再入力）が必要というバリデーションを追加してる

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }
  validate :agreement
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true


  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  attr_accessor :agree_terms

  def agreement
    if new_record?
      unless agree_terms == "1" || agree_terms == true
        errors.add(:agree_terms, "に同意されてません")
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  add_flash_types :success, :danger

  private

  def redirect_if_logged_in
    if logged_in?
      redirect_to root_path, success: t("flash_message.logged_in")
    end
  end

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  def oauth
    login_at(auth_params[:provider])
    # 指定されたプロバイダの認証ページにユーザーをリダイレクトさせる
  end

  def callback
    provider = auth_params[:provider]
    if (@user = login_from(provider))
      # 既存のユーザーをプロバイダ情報を元に検索し、存在すればログイン
      redirect_to root_path, success: t("flash_message.google_login_success")
    else
      begin
        signup_and_login(provider)
        # ユーザーが存在しない場合はプロバイダ情報を元に新規ユーザーを作成し、ログイン

        redirect_to root_path, success: t("flash_message.google_login_success")
      rescue StandardError => e
        # Rubyの例外クラスの一つ。rescueの部分で発生した例外を捕まえ、「e」に格納する
        redirect_to root_path, danger: t("flash_message.google_login_failure")
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider, :scope, :authuser, :prompt)
  end

  def signup_and_login(provider)
    @user = create_from(provider)
    reset_session
    auto_login(@user)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :redirect_if_logged_in, only: %i[new create edit update]

  def new; end

  def create
    @user = User.find_by(email: params[:email])
    @user&.deliver_reset_password_instructions!
    # ランダムなトークンを含むURLを記載したメールをユーザーに送信
    redirect_to login_path, success: t("flash_message.password_reset_request_sending")
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])
    not_authenticated if @user.blank?
  end
  # 「load_from_reset_password_token」はsorcery のメソッド。
  # 与えられたトークンを使ってユーザーを検索し、該当するユーザーオブジェクトを返す。
  # もしトークンが無効だったり、ユーザーが見つからなかったりすると、nil を返すことになる。

  # 「not_authenticated」はユーザーが認証されていない場合に呼び出されるメソッド。applicationコントローラーに記載。

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    return not_authenticated if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password(params[:user][:password])
      redirect_to login_path
      flash[:success]= t("flash_message.password_reset_completion")
    else
      flash.now[:danger] = t("flash_message.failure")
      render :edit, status: :unprocessable_entity
    end
  end
  # 「change_password」はsorceryのメソッド。新しいパスワードをユーザーオブジェクトに設定し、パスワードを更新する処理を実行。
  # 成功でtrue、失敗（確認用のパスワードと異なる場合）でfalseを返す。
  # 「@user.password_confirmation」は後のif文がfalseでも値が更新されたままになりそうだけど弊害はなさそう。
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_login, only: %i[destroy]
  before_action :redirect_if_logged_in, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, success: t("flash_message.login_success")
    else
      flash.now[:danger] = t("flash_message.login_failure")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:success] = t("flash_message.logout")
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[show edit update]

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t("flash_message.user_create")
    else
      flash.now[:danger] = t("flash_message.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to user_path(current_user), success: t("flash_message.update_success")
    else
      flash.now[:danger] = t("flash_message.update_failure")
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @users = User.all  # すべてのユーザーを取得
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :agree_terms)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = "")   # メソッドが呼ばれたときに引数が渡されなかった場合に、デフォルトで空の文字列を使う意味
    @base_title = "グラブルTA計算アプリ"
    title.present? ? "#{title} | #{@base_title}" : @base_title
  end

  def default_meta_tags
    {
      site: "グラブルTA計算アプリ",
      title: "グラブルTA計算アプリ",
      reverse: true,
      charset: "utf-8",
      description: "パーティメンバー全員のTA率を確認しながら編成を組む際に役に立ちます。このアプリは、ブラウザゲーム「グランブルーファンタジー」におけるTA率（トリプルアタック率）の計算を行うアプリです",
      keywords: "グラブル,グランブルーファンタジー,GRANBLUE FANTASY,TA,TA率,計算ツール,計算アプリ,計算,ツール,アプリ,トリプルアタック",
      canonical: "https://graburu-triple-attack-app.com",
      separator: "|",
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: "website",
        url: "https://graburu-triple-attack-app.com",
        image: image_url("ogp.png"),
        local: "ja-JP"
      },
      twitter: {
        card: "summary",
        site: "@bfkjs8",
        image: image_url("ogp.png")
      }
    }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/formations/_forte_weapon_list.html.erb
<input type="checkbox" name="forte_weapon_character_<%= id %>" value="1" id="forte-weapon-character-<%= id %>-option-1">
<label for="forte-weapon-character-<%= id %>-option-1">剣</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="2" id="forte-weapon-character-<%= id %>-option-2">
<label for="forte-weapon-character-<%= id %>-option-2">短剣</label> 

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="3" id="forte-weapon-character-<%= id %>-option-3">
<label for="forte-weapon-character-<%= id %>-option-3">槍</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="4" id="forte-weapon-character-<%= id %>-option-4">
<label for="forte-weapon-character-<%= id %>-option-4">斧</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="5" id="forte-weapon-character-<%= id %>-option-5">
<label for="forte-weapon-character-<%= id %>-option-5">杖</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="6" id="forte-weapon-character-<%= id %>-option-6">
<label for="forte-weapon-character-<%= id %>-option-6">銃</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="7" id="forte-weapon-character-<%= id %>-option-7">
<label for="forte-weapon-character-<%= id %>-option-7">格闘</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="8" id="forte-weapon-character-<%= id %>-option-8">
<label for="forte-weapon-character-<%= id %>-option-8">弓</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="9" id="forte-weapon-character-<%= id %>-option-9">
<label for="forte-weapon-character-<%= id %>-option-9">楽器</label>

<input type="checkbox" name="forte_weapon_character_<%= id %>" value="10" id="forte-weapon-character-<%= id %>-option-10">
<label for="forte-weapon-character-<%= id %>-option-10">刀</label>

app/views/formations/_members_status_up_infomation.html.erb
<div class="item-title mt-3">
  <p>メンバー<%= id %>のステータス上昇要素</p>
</div>

<div>
  <p>アーティファクト</p>
  <input type="number" class="box" name="artifact_character_<%= id %>">
</div>

<div>
  <p>リミットボーナス</p>
  <input type="number" class="box" name="limit_bonus_character_<%= id %>">
</div>

<div>
  <p>指輪、耳飾り</p>
  <input type="number" class="box" name="ring_character_<%= id %>">
</div>

<div>
  <p>連続攻撃覚醒lv9</p>

  <select id="consecutive_attack_character_<%= id %>">
    <option value="0">無</option>
    <option value="1">有</option>
  </select>
</div>

<div>
  <p>その他要因（スキル効果（単体）など）</p>
  <input type="number" class="box" name="skill_single_character_<%= id %>">
</div>

app/views/formations/_omega_and_star_weapon.html.erb
<input type="radio" name="<%= weapon_name %>" value="0" id="<%= weapon_name %>-0" checked>
<label for="<%= weapon_name %>-0">無</label>

<input type="radio" name="<%= weapon_name %>" value="1" id="<%= weapon_name %>-1">
<label for="<%= weapon_name %>-1">剣</label>

<input type="radio" name="<%= weapon_name %>" value="2" id="<%= weapon_name %>-2">
<label for="<%= weapon_name %>-2">短剣</label>

<input type="radio" name="<%= weapon_name %>" value="3" id="<%= weapon_name %>-3">
<label for="<%= weapon_name %>-3">槍</label>

<input type="radio" name="<%= weapon_name %>" value="4" id="<%= weapon_name %>-4">
<label for="<%= weapon_name %>-4">斧</label>

<input type="radio" name="<%= weapon_name %>" value="5" id="<%= weapon_name %>-5">
<label for="<%= weapon_name %>-5">杖</label>

<input type="radio" name="<%= weapon_name %>" value="6" id="<%= weapon_name %>-6">
<label for="<%= weapon_name %>-6">銃</label>

<input type="radio" name="<%= weapon_name %>" value="7" id="<%= weapon_name %>-7">
<label for="<%= weapon_name %>-7">格闘</label>

<input type="radio" name="<%= weapon_name %>" value="8" id="<%= weapon_name %>-8">
<label for="<%= weapon_name %>-8">弓</label>

<input type="radio" name="<%= weapon_name %>" value="9" id="<%= weapon_name %>-9">
<label for="<%= weapon_name %>-9">楽器</label>

<input type="radio" name="<%= weapon_name %>" value="10" id="<%= weapon_name %>-10">
<label for="<%= weapon_name %>-10">刀</label>

app/views/formations/_three_moves_options.html.erb
<div>
  <label><%= label %></label>
  <select id="<%= id %>">
    <option value="0">0本</option>
    <option value="1">1本</option>
    <option value="2">2本</option>
    <option value="3">3本</option>
    <option value="4">4本</option>
    <option value="5">5本</option>
    <option value="6">6本</option>
    <option value="7">7本</option>
    <option value="8">8本</option>
    <option value="9">9本</option>
  </select>
</div>

app/views/formations/test_1.html.erb
テストページ

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%# application_helperのpage_titleメソッドの呼び出し。各ビューのcontent_forの:titleがここに代入される。 %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <%= display_meta_tags(default_meta_tags) %>

    <% if Rails.env.production? %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-53ZQNNNF0X"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-53ZQNNNF0X');
      </script>
    <% end %>
  </head>

  <body class="d-flex flex-column min-vh-100 bg-primary-subtle">
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <div class="flex-grow-1">
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<% content_for(:title, t(".page_title")) %>


<div class="container">
  <div class="row mt-3">
    <h3><%= t(".password_reset") %></h3>

    <%= form_with model: @user, url: password_reset_path(@token) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :email %>
        <%= @user.email %>
      </div>

      <div class="mt-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="mt-3">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="mt-3">
        <%= f.submit t("helpers.submit.reset") %>
      </div>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% content_for(:title, t(".page_title")) %>


<div class="container">
  <div class="row">
    <h3><%= t(".password_reset_request") %></h3>
    <%= t(".password_reset_request_info") %>
    <div class="mt-3">
      <%= form_with url: password_resets_path do |f| %>
        <%= f.label :email %>
        <%= f.email_field :email %>
        <%= f.submit t("helpers.submit.request") %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<div class="container bg-info">
  <div class="row py-2 justify-content-between">
    <div class="col-auto">
      <%= link_to root_path, class: "btn btn-light" do %>
        <div class="d-flex align-items-center">
          <div>
            <%= image_tag "gbapp_title.png" %>
          </div>
          <div class="ms-2">
            <p><%= t(".app_title") %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-auto pt-2">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t(".menu") %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <li><%= link_to t(".to_register_page"), new_user_path, class: 'dropdown-item' %></li>
          <li><%= link_to t(".to_login_page"), login_path, class: 'dropdown-item' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container bg-info mt-5">
  <div class="row">
    <div class="d-flex justify-content-start">
      <%= link_to t(".inquiry"), "https://docs.google.com/forms/d/e/1FAIpQLScMEnGt5KXUJI8sgH2Jf0so4gfufuBczf9GyQERBC-hTy_gKQ/viewform?usp=header", class: "col-2 my-3 text-black text-decoration-none" %>
      <%= link_to t(".agree_terms"), terms_path, class: "col-2 my-3 text-black text-decoration-none" %>
      <%= link_to t(".privacy_policy"), policy_path, class: "col-3 my-3 text-black text-decoration-none" %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="container bg-info">
  <div class="row py-2 justify-content-between">
    <div class="col-auto">
      <%= link_to root_path, class: "btn btn-light" do %>
        <div class="d-flex align-items-center">
          <div>
            <%= image_tag "gbapp_title.png" %>
          </div>
          <div class="ms-2">
            <p><%= t(".app_title") %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-auto">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t(".menu") %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <li><%= link_to t(".my_page"), user_path(current_user), class: 'dropdown-item' %></li>
          <li><%= link_to t(".logout"), logout_path, data: { turbo_method: :delete }, class: 'dropdown-item' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="container">
  <div>
    <div class="d-flex">
      <% unless logged_in? %>
        <div class="me-3">
          <%= link_to t(".to_register_page"), new_user_path %>
        </div>
        <div>
          <%= link_to t(".to_login_page"), login_path %>
        </div>
      <% end %>
    </div>

    <div class="mt-3">
      <h1>グラブルTA計算アプリ</h1>
    </div>
    
    <%# -----ーーーーーーーー新規機能テスト用ーーーーーーーーーー----- %>
    <%# link_to "テストページへ", test_1_formations_path %>

    <div class="mt-3">
      <%= link_to new_formation_path, class: "btn" do %>
        <p>画像クリックで計算ページへ</p>
        <div class="d-flex align-items-center">
          <div>
            <%= image_tag "ogp.png" %>
          </div>
        </div>
      <% end %>
    </div>

    <hr class="my-4 mt-5">
    <%# -----HTMLの水平線を描画するタグ----- %>

    <div class="bg-info-subtle p-3">
      <div class="mt-3">
        <h3 class="text-center">このアプリは、ブラウザゲーム「グランブルーファンタジー」におけるTA率(トリプルアタック率)の計算を目的としたアプリです</h3>
      </div>

      <div class="mt-3">
        <h5 class="text-center">〜当アプリの使い方〜</h5>
      </div>

      <div class="mt-4">
        <p class="text-center">基本機能使用にログインは必要ありません</p>
        <p class="text-center">TA上昇武器、オメガ武器、召喚石、キャラクターごとの上昇値などの項目を埋めていくと自動でキャラクターごとのTA率を算出します (項目はすべて埋める必要はありません)</p>
        <p class="text-center">「パーティ4人のTA率を100%にしつつ火力も最大限出したい！」</p>
        <p class="text-center">そのような編成を組む、試行錯誤の際ご活用ください</p>
      </div>
    </div>

    <hr class="my-4 mt-5">
    <%# -----HTMLの水平線を描画するタグ----- %>

    <div class="bg-info-subtle p-3">
      <div class="mt-3">
        <h3 class="text-center">ログインをすると？</h3>
      </div>

      <div class="mt-4">
        <p class="text-center">まだ未実装ですが今後埋めた項目、TA率計算の情報を保存する機能を追加予定です</p>
      </div>
    </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<% content_for(:title, t(".page_title")) %>

<div class="container">
  <div class="row">
    <h1><%= t(".login") %></h1>

    <%= form_with url: login_path do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <div class="mt-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
  
      <div class="mt-3">
        <%= f.submit t('.login'), class: "btn btn-primary" %>
      </div>
    <% end %>

    <%# ---------↓googleログイン部分--------- %>

    <hr class="my-4">
    <%# -----HTMLの水平線を描画するタグ----- %>

    <div class="d-flex justify-content-center">
      <div>

        <div class="mb-3">
          <h5><%= t(".or_login_with_your_google_account") %></h5>
        </div>

        <div>
          <%= link_to auth_at_provider_path(provider: :google) do %>
            <%= image_tag "sign_in@2x.png" %>
          <% end %>
        </div>

      </div>
    </div>

    <hr class="my-4">

    <%# ---------googleログイン部分--------- %>

    <div class='text-center'>
      <%= link_to t(".to_register_page"), new_user_path %>
      <%= link_to t(".forgot_password?"), new_password_reset_path %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, t(".page_title")) %>


<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t(".user_registration") %></h1>
      <%# ---------補足: registration 登録--------- %>

      <%= form_with model: @user do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="mb-3">
          <%= f.label :name, t(".name_required"), class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :email, t(".email_required"), class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password, t(".password_required"), class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password_confirmation, t(".password_confirmation_required"), class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :agree_terms, t(".accept_terms_of_use") %>
          <%= f.check_box :agree_terms %>
          <%# ---------補足: agree_terms 利用規約, accept_terms_of_use 利用規約に同意しますか？--------- %>
        </div>

        <div class="mb-3">
          <%= link_to t(".agree_terms"), terms_path %>
          <%= link_to t(".privacy_policy"), policy_path %>
        </div>

        <%= f.submit t("helpers.submit.create"), class: "btn btn-primary" %>

      <% end %>

      <%# ---------↓googleログイン部分--------- %>

      <hr class="my-4">

      <div class="d-flex justify-content-center">
        <div>

          <div class="mb-3">
            <h5><%= t(".or_register_with_your_google_account") %></h5>
          </div>

          <div>
            <%= link_to auth_at_provider_path(provider: :google) do %>
              <%= image_tag "sign_up@2x.png" %>
            <% end %>
          </div>

        </div>
      </div>

      <hr class="my-4">

      <%# ---------googleログイン部分--------- %>

      <div class='text-center'>
        <%= link_to t(".to_login_page"), login_path %>
        <%= link_to t(".to_top_page"), root_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>ユーザー情報</h1>
<p>ネーム：<%= @user.name %>さん</p>
<p>Email: <%= @user.email %></p>


<%= link_to t(".your_account_information"), edit_user_path(current_user) %>